mode: "single" # Choose "single" or "ablation"

project:
  version: "1.2.3"
  run_name: "gae_test"

seeds:
  train: [0, 42]
  test: [1000, 2000, 3000]

env:
  id: "highway-v0"
  render_mode: "rgb_array"

env_config:
  observation:
    type: "Kinematics"
    vehicles_count: 15
  action:
    type: "DiscreteMetaAction"
  lanes_count: 2
  vehicles_count: 60
  duration: 50
  initial_spacing: 2
  simulation_frequency: 10
  ego_spacing: 1.5

# Configuration for a single standard run
single_run:
  agent:
    type: "A2CAgent"  # "REINFORCEAgent" or "A2CAgent"
    gamma: 0.99
    lr: 0.001
    episodes: 60
    save_agent_every: 50
    update_every: 30
    # REINFORCE
    hidden_size: [32, 16]
    #A2C
    actor_hidden_size: [32, 16]
    critic_hidden_size: [32, 16]
    use_gae: True
    gae_lambda: 0.95

# Configuration for the ablation study run
ablation:
  experiments:
    - name: "REINFORCE"
      agent:
        type: "REINFORCEAgent"
        gamma: 0.99
        lr: 0.001
        hidden_size: [32, 16]
        episodes: 150
        save_agent_every: 151
        update_every: 1
    - name: "A2C"
      agent:
        type: "A2CAgent"
        gamma: 0.99
        lr: 0.001
        actor_hidden_size: [32, 16]
        critic_hidden_size: [32, 16]
        episodes: 150
        save_agent_every: 151
        update_every: 10