project:
  version: "1.3.0"
  ablation_name: "reinforce_vs_a2c"

# Seeds for the study
seeds:
  train: [0, 42, 123]
  test: [1000, 2000, 3000]

# List of experiments to run
experiments:
  - name: "REINFORCE"
    agent:
      type: "REINFORCEAgent"
      gamma: 0.99
      lr: 0.001
      hidden_size: [32,16]
      episodes: 200
      save_agent_every: 201 # Disable intermediate saving
      update_every: 1 # Not used but required
  - name: "A2C (update_every=10)"
    agent:
      type: "A2CAgent"
      gamma: 0.99
      lr: 0.001
      actor_hidden_size: [32,16]
      critic_hidden_size: [32,16]
      episodes: 200
      save_agent_every: 201 # Disable intermediate saving
      update_every: 10

# Common env config for all experiments
env:
  id: "highway-v0"
  render_mode: "rgb_array"

env_config:
  observation:
    type: "Kinematics"
    vehicles_count: 15
  action:
    type: "DiscreteMetaAction"
  lanes_count: 2
  vehicles_count: 60
  duration: 50
  initial_spacing: 2
  simulation_frequency: 10
  ego_spacing: 1.5